import React, { createContext, useContext, useState, useEffect } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

type Language = "en" | "hi" | "kn" | "pa" | "ta" | "te" | "es" | "zh" | "ur";

interface LanguageContextType {
  language: Language | null;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome to Skrillz",
    select_lang: "Select your language",
    continue: "Continue",
    login: "Sign In",
    signup: "Sign Up",
    home: "Home",
    appointments: "Appointments",
    profile: "Profile",
    request_appointment: "Request Appointment",
    book_now: "Book Now",
    search_doctor: "Search for doctors...",
    welcome_back: "Welcome Back",
    login_subtitle: "Sign in to continue your journey",
    email_placeholder: "Enter your email or ID",
    pass_placeholder: "Enter your password",
    forgot_pass: "Forgot Password?",
    no_account: "Don't have an account?",
    already_account: "Already have an account?",
    create_account: "Create Account",
    join_today: "Join SKRILZ today",
    personal_info: "Personal Information",
    i_am_a: "I am a...",
    doctor_role: "Doctor",
    patient_role: "Patient",
    student_role: "Student",
    or: "OR",
    continue_with_apple: "Continue with Apple",
    continue_with_google: "Continue with Google",
    continue_with_linkedin: "Continue with LinkedIn",
    quick_actions: "Quick Actions",
    health_stats: "Your Health Stats",
    upcoming_apps: "Upcoming Appointments",
    recommended_docs: "Recommended Doctors",
    view_details: "View Details",
    view_all: "View All",
    join: "Join",
    rebook: "Re-Book Appointment",
    medical_essentials: "Medical Essentials",
    total_earning: "Total Earning",
    virtual_clinic: "Virtual Clinic",
    earning_potential: "Earning Potential",
    professional: "Professional",
    upcoming_meetings: "Upcoming Meetings",
    pending_reports: "Pending Patient Reports",
    open_records: "Open Records",
    review: "Review",
    my_appointments: "My Appointments",
    upcoming: "Upcoming",
    history: "History",
    accepted: "Accepted",
    suggested: "Suggested",
    confirm_time: "Confirm Time",
    select_date: "Select Date",
    reason: "Reason for visit",
    status_pending: "Pending",
    status_accepted: "Accepted",
    status_cancelled: "Cancelled",
    messages: "Messages",
    type_message: "Type a message...",
    online: "Online",
    offline: "Offline",
    start_call: "Start Call",
    end_call: "End Call",
    mute: "Mute",
    video_on: "Video On",
    video_off: "Video Off",
    health_status: "Health Status",
    medical_records: "Medical Records",
    prescriptions: "Prescriptions",
    recommended_doctors: "Recommended Doctors",
    contact_support: "Contact Support",
    change_language: "Change Language",
    choose_doctor_date: "Choose doctor & date",
    select_doctor: "Select Doctor",
    consult_type: "Consultation Type",
    video_call: "Video Call",
    audio_call: "Audio Call",
    clinic_visit: "Clinic Visit",
    payment_summary: "Payment Summary",
    consult_fee: "Consultation Fee",
    platform_charges: "Platform Charges",
    total_payable: "Total Payable",
    all_appointments: "All Appointments",
    manage_schedule: "Manage your consultation schedule",
    search_patient: "Search patient name...",
    select_time_title: "Select Consultation Time:",
    accept_set_time: "Accept & Set Time",
    view_report: "View Report",
    no_apps_found: "No appointments found",
    search_patient_msg: "Search patient or message...",
    search_doctor_msg: "Search doctor or message...",
    active_now: "Active Now",
    patient_history: "Patient History",
    upload_prescription_report: "Upload Prescription / Report",
    health_profile: "Health Profile",
    manage_health_info: "Manage your personal health information",
    basic_info: "Basic Information",
    height: "Height (cm)",
    weight: "Weight (kg)",
    blood_group: "Blood Group",
    medical_history: "Medical History",
    existing_conditions: "Existing Conditions (e.g. heart attack, diabetes)",
    past_surgeries: "Past Surgeries / Hospitalizations",
    lifestyle: "Lifestyle",
    save_profile: "Save Health Profile",
    upload_manage_health: "Upload and manage your health documents",
    uploaded_by: "Uploaded by",
    view: "View",
    download: "Download",
    delete: "Delete",
    choose_action: "Choose an action",
    upload_pdf_img: "Upload PDF / Image",
    camera_scan: "Camera (Scan)",
    active_medications: "Active Medications",
    prescription_history: "Prescription History",
    dr_dosage: "Dr. / Dosage",
    instruction: "Instruction",
    ordered_on: "Ordered on",
    issued_by: "Issued by",
    order_meds: "Order Medications",
    medical_prescription: "Medical Prescription",
    reg_no: "Reg No",
    patient: "Patient",
    date: "Date",
    age: "Age",
    frequency: "Frequency",
    duration: "Duration",
    instructions: "Instructions",
    doctors_notes: "Doctor's Notes",
    print: "Print",
    choose_doctor_profile_msg: "Choose a doctor and view full profile",
    consultation: "Consultation",
    low: "Low",
    moderate: "Moderate",
    high: "High",
  },
  hi: {
    welcome: "Skrillz में आपका स्वागत है",
    select_lang: "अपनी भाषा चुनें",
    continue: "आगे बढ़ें",
    login: "साइन इन करें",
    signup: "साइन अप करें",
    home: "होम",
    appointments: "अपॉइंटमेंट",
    profile: "प्रोफ़ाइल",
    request_appointment: "अपॉइंटमेंट का अनुरोध करें",
    book_now: "अभी बुक करें",
    search_doctor: "डॉक्टरों की खोज करें...",
    welcome_back: "वापसी पर स्वागत है",
    login_subtitle: "अपनी यात्रा जारी रखने के लिए साइन इन करें",
    email_placeholder: "अपना ईमेल या आईडी दर्ज करें",
    pass_placeholder: "अपना पासवर्ड दर्ज करें",
    forgot_pass: "पासवर्ड भूल गए?",
    no_account: "क्या आपका अकाउंट नहीं है?",
    already_account: "पहले से ही एक अकाउंट है?",
    create_account: "अकाउंट बनाएं",
    join_today: "आज ही SKRILZ से जुड़ें",
    personal_info: "व्यक्तिगत जानकारी",
    i_am_a: "मैं एक... हूँ",
    doctor_role: "डॉक्टर",
    patient_role: "मरीज",
    student_role: "छात्र",
    or: "या",
    continue_with_apple: "Apple के साथ जारी रखें",
    continue_with_google: "Google के साथ जारी रखें",
    continue_with_linkedin: "LinkedIn के साथ जारी रखें",
    quick_actions: "त्वरित कार्रवाई",
    health_stats: "आपके स्वास्थ्य आँकड़े",
    upcoming_apps: "आने वाले अपॉइंटमेंट",
    recommended_docs: "अनुशंसित डॉक्टर",
    view_details: "विवरण देखें",
    view_all: "सभी देखें",
    join: "जुड़ें",
    rebook: "अपॉइंटमेंट फिर से बुक करें",
    medical_essentials: "चिकित्सा संबंधी आवश्यक वस्तुएं",
    total_earning: "कुल कमाई",
    virtual_clinic: "वर्चुअल क्लिनिक",
    earning_potential: "कमाई की संभावना",
    professional: "पेशेवर",
    upcoming_meetings: "आने वाली बैठकें",
    pending_reports: "लंबित मरीज रिपोर्ट",
    open_records: "रिकॉर्ड खोलें",
    review: "समीक्षा करें",
    my_appointments: "मेरे अपॉइंटमेंट",
    upcoming: "आने वाले",
    history: "इतिहास",
    accepted: "स्वीकार किए गए",
    suggested: "सुझाए गए",
    confirm_time: "समय की पुष्टि करें",
    select_date: "तारीख चुनें",
    reason: "आने का कारण",
    status_pending: "लंबित",
    status_accepted: "स्वीकृत",
    status_cancelled: "रद्द",
    messages: "संदेश",
    type_message: "एक संदेश लिखें...",
    online: "ऑनलाइन",
    offline: "ऑफ़लाइन",
    start_call: "कॉल शुरू करें",
    end_call: "कॉल समाप्त करें",
    mute: "म्यूट",
    video_on: "वीडियो चालू",
    video_off: "वीडियो बंद",
    health_status: "स्वास्थ्य स्थिति",
    medical_records: "मेडिकल रिकॉर्ड",
    prescriptions: "नुस्खे",
    recommended_doctors: "अनुशंसित डॉक्टर",
    contact_support: "सहायता केंद्र",
    change_language: "भाषा बदलें",
    choose_doctor_date: "डॉक्टर और तारीख चुनें",
    select_doctor: "डॉक्टर चुनें",
    consult_type: "परामर्श का प्रकार",
    video_call: "वीडियो कॉल",
    audio_call: "ऑडियो कॉल",
    clinic_visit: "क्लीनिक विजिट",
    payment_summary: "भुगतान सारांश",
    consult_fee: "परामर्श शुल्क",
    platform_charges: "प्लेटफ़ॉर्म शुल्क",
    total_payable: "कुल देय",
    all_appointments: "सभी अपॉइंटमेंट",
    manage_schedule: "अपने परामर्श कार्यक्रम का प्रबंधन करें",
    search_patient: "रोगी का नाम खोजें...",
    select_time_title: "परामर्श का समय चुनें:",
    accept_set_time: "स्वीकार करें और समय निर्धारित करें",
    view_report: "रिपोर्ट देखें",
    no_apps_found: "कोई अपॉइंटमेंट नहीं मिला",
    search_patient_msg: "रोगी या संदेश खोजें...",
    search_doctor_msg: "डॉक्टर या संदेश खोजें...",
    active_now: "अभी सक्रिय",
    patient_history: "रोगी का इतिहास",
    upload_prescription_report: "प्रिस्क्रिप्शन / रिपोर्ट अपलोड करें",
    health_profile: "स्वास्थ्य प्रोफ़ाइल",
    manage_health_info: "अपनी व्यक्तिगत स्वास्थ्य जानकारी प्रबंधित करें",
    basic_info: "बुनियादी जानकारी",
    height: "ऊंचाई (cm)",
    weight: "वजन (kg)",
    blood_group: "रक्त समूह",
    medical_history: "चिकित्सा इतिहास",
    existing_conditions: "मौजूदा स्थितियां (जैसे दिल का दौरा, मधुमेह)",
    past_surgeries: "पिछली सर्जरी / अस्पताल में भर्ती",
    lifestyle: "जीवनशैली",
    save_profile: "स्वास्थ्य प्रोफ़ाइल सहेजें",
    upload_manage_health: "अपने स्वास्थ्य दस्तावेज़ अपलोड और प्रबंधित करें",
    uploaded_by: "द्वारा अपलोड किया गया",
    view: "देखیں",
    download: "डाउनलोड करें",
    delete: "हटाएं",
    choose_action: "एक क्रिया चुनें",
    upload_pdf_img: "PDF / छवि अपलोड करें",
    camera_scan: "कैमरा (स्कैन)",
    active_medications: "सक्रिय दवाएं",
    prescription_history: "नुस्खा इतिहास",
    dr_dosage: "डॉक्टर / खुराक",
    instruction: "निर्देश",
    ordered_on: "को आदेश दिया गया",
    issued_by: "द्वारा जारी किया गया",
    order_meds: "दवाएं ऑर्डर करें",
    medical_prescription: "चिकित्सा नुस्खा",
    reg_no: "पंजीकरण संख्या",
    patient: "मरीज",
    date: "दिनांक",
    age: "आयु",
    frequency: "आवृत्ति",
    duration: "अवधि",
    instructions: "निर्देश",
    doctors_notes: "डॉक्टर के नोट्स",
    print: "प्रिंट करें",
    low: "कम",
    moderate: "मध्यम",
    high: "उच्च",
  },
  kn: {
    welcome: "Skrillz ಗೆ ಸ್ವಾಗತ",
    select_lang: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    continue: "ಮುಂದುವರಿಸಿ",
    login: "ಸೈನ್ ಇನ್",
    signup: "ಸೈನ್ ಅಪ್",
    home: "ಮುಖಪುಟ",
    appointments: "ನೇಮಕಾತಿಗಳು",
    profile: "ಪ್ರೊಫೈಲ್",
    request_appointment: "ನೇಮಕಾತಿ ವಿನಂತಿಸಿ",
    book_now: "ಈಗಲೇ ಕಾಯ್ದಿರಿಸಿ",
    search_doctor: "ವೈದ್ಯರಿಗಾಗಿ ಹುಡುಕಿ...",
    welcome_back: "ಮರಳಿ ಸ್ವಾಗತ",
    login_subtitle: "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
    email_placeholder: "ನಿಮ್ಮ ಇಮೇಲ್ ಅಥವಾ ಐಡಿ ನಮೂದಿಸಿ",
    pass_placeholder: "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",
    forgot_pass: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    no_account: "ಖಾತೆ ಇಲ್ಲವೇ?",
    already_account: "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?",
    create_account: "ಖಾತೆ ರಚಿಸಿ",
    join_today: "ಇಂದೇ SKRILZ ಗೆ ಸೇರಿ",
    personal_info: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
    i_am_a: "ನಾನು ಒಬ್ಬ...",
    doctor_role: "ವೈದ್ಯ",
    patient_role: "ರೋಗಿ",
    student_role: "ವಿದ್ಯಾರ್ಥಿ",
    or: "ಅಥವಾ",
    continue_with_apple: "Apple ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    continue_with_google: "Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    continue_with_linkedin: "LinkedIn ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    quick_actions: "ತ್ವರಿತ ಕ್ರಮಗಳು",
    health_stats: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಅಂಕಿಅಂಶಗಳು",
    upcoming_apps: "ಮುಂಬರುವ ನೇಮಕಾತಿಗಳು",
    recommended_docs: "ಶಿಫಾರಸು ಮಾಡಿದ ವೈದ್ಯರು",
    view_details: "ವಿವರಗಳನ್ನು ನೋಡಿ",
    view_all: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    join: "ಸೇರಿ",
    rebook: "ನೇಮಕಾತಿಯನ್ನು ಮತ್ತೆ ಕಾಯ್ದಿರಿಸಿ",
    medical_essentials: "ವೈದ್ಯಕೀಯ ಅಗತ್ಯಗಳು",
    total_earning: "ಒಟ್ಟು ಗಳಿಕೆ",
    virtual_clinic: "ವರ್ಚುವಲ್ ಕ್ಲಿನಿಕ್",
    earning_potential: "ಗಳಿಕೆಯ ಸಾಮರ್ಥ್ಯ",
    professional: "ವೃತ್ತಿಪರ",
    upcoming_meetings: "ಮುಂಬರುವ ಸಭೆಗಳು",
    pending_reports: "ಬಾಕಿ ಇರುವ ರೋಗಿಗಳ ವರದಿಗಳು",
    open_records: "ದಾಖಲೆಗಳನ್ನು ತೆರೆಯಿರಿ",
    review: "ಪರಿಶೀಲಿಸಿ",
    my_appointments: "ನನ್ನ ನೇಮಕಾತಿಗಳು",
    upcoming: "ಮುಂಬರುವ",
    history: "ಇತಿಹಾಸ",
    accepted: "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    suggested: "ಸೂಚಿಸಲಾಗಿದೆ",
    confirm_time: "ಸಮಯವನ್ನು ಖಚಿತಪಡಿಸಿ",
    select_date: "ದಿನಾಂಕವನ್ನು ಆರಿಸಿ",
    reason: "ಭೇಟಿಗೆ ಕಾರಣ",
    status_pending: "ಬಾಕಿ ಇದೆ",
    status_accepted: "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    status_cancelled: "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ",
    messages: "ಸಂದೇಶಗಳು",
    type_message: "ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    online: "ಆನ್‌ಲೈನ್",
    offline: "ಆಫ್‌ಲೈನ್",
    start_call: "ಕರೆ ಪ್ರಾರಂಭಿಸಿ",
    end_call: "ಕರೆ ಕೊನೆಗೊಳಿಸಿ",
    mute: "ನಿಶ್ಯಬ್ದ",
    video_on: "ವಿಡಿಯೋ ಆನ್",
    video_off: "ವಿಡಿಯೋ ಆಫ್",
    health_status: "ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
    medical_records: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
    prescriptions: "ಔಷಧಿ ಚೀಟಿಗಳು",
    recommended_doctors: "ಶಿಫಾರಸು ಮಾಡಿದ ವೈದ್ಯರು",
    contact_support: "ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ",
    change_language: "ಭಾಷೆಯನ್ನು ಬದಲಿಸಿ",
    choose_doctor_date: "ವೈದ್ಯರು ಮತ್ತು ದಿನಾಂకವನ್ನು ఆರಿಸಿ",
    select_doctor: "ವೈದ್ಯರನ್ನು ఆರಿಸಿ",
    consult_type: "సమాలోచనర ప్రకార",
    video_call: "విడియో ಕರೆ",
    audio_call: "ಆಡಿಯೋ ಕರೆ",
    clinic_visit: "ಕ್ಲಿನಿಕ್ ಭೇಟಿ",
    payment_summary: "ಪಾವತಿ ಸಾರಾಂಶ",
    consult_fee: "ಸಮಾಲೋಚನೆ ಶುಲ್ಕ",
    platform_charges: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕಗಳು",
    total_payable: "ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
    all_appointments: "ಎಲ್ಲಾ ನೇಮಕಾತಿಗಳು",
    manage_schedule: "ನಿಮ್ಮ ಸಮಾಲೋಚನೆ ವೇಳಾಪಟ್ಟಿಯನ್ನು ನಿರ್ವಹಿಸಿ",
    search_patient: "ರೋಗಿಯ ಹೆಸರನ್ನು ಹುಡುಕಿ...",
    select_time_title: "ಸಮಾಲೋಚನೆ ಸಮಯವನ್ನು ಆರಿಸಿ:",
    accept_set_time: "ಸ್ವೀಕರಿಸಿ ಮತ್ತು ಸಮಯವನ್ನು ನಿಗದಿಪಡಿಸಿ",
    view_report: "ವರದಿಯನ್ನು ನೋಡಿ",
    no_apps_found: "ಯಾವುದೇ ನೇಮಕಾತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    search_patient_msg: "ರೋಗಿ ಅಥವಾ ಸಂದೇಶವನ್ನು ಹುಡುಕಿ...",
    search_doctor_msg: "ವೈದ್ಯರು ಅಥವಾ ಸಂದೇಶವನ್ನು ಹುಡುಕಿ...",
    active_now: "ಈಗ ಸಕ್ರಿಯವಾಗಿದೆ",
    patient_history: "ರೋಗಿಯ ಇತಿಹಾಸ",
    upload_prescription_report: "ಔಷಧಿ ಚೀಟಿ / ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    health_profile: "ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್",
    manage_health_info: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಆರೋಗ್ಯ ಮಾಹಿತಿಯನ್ನು ನಿರ್ವಹಿಸಿ",
    basic_info: "ಮೂಲ ಮಾಹಿತಿ",
    height: "ಎತ್ತರ (cm)",
    weight: "ತೂಕ (kg)",
    blood_group: "ರಕ್ತದ ಗುಂಪು",
    medical_history: "ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ",
    existing_conditions: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಪರಿಸ್ಥಿತಿಗಳು (ಉದಾ. ಹೃದಯಾಘಾತ, ಮಧುಮೇಹ)",
    past_surgeries: "ಹಿಂದಿನ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಗಳು / ಆಸ್ಪತ್ರೆಗೆ ದಾಖಲಾಗಿರುವುದು",
    lifestyle: "ಜೀವನಶೈಲಿ",
    save_profile: "ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    upload_manage_health: "ನಿಮ್ಮ ಆರೋಗ್ಯ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ",
    uploaded_by: "ಇವರಿಂದ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ",
    view: "ನೋಡಿ",
    download: "ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    delete: "ಅಳಿಸಿ",
    choose_action: "ಒಂದು ಕ್ರಿಯೆಯನ್ನು ಆರಿಸಿ",
    upload_pdf_img: "PDF / ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    camera_scan: "ಕ್ಯಾಮೆರಾ (ಸ್ಕ್ಯಾನ್)",
    active_medications: "ಸಕ್ರಿಯ ಔಷಧಿಗಳು",
    prescription_history: "ಔಷಧಿ ಚೀಟಿ ಇತಿಹಾಸ",
    dr_dosage: "ವೈದ್ಯರು / ಡೋಸೇಜ್",
    instruction: "ಸೂಚನೆ",
    ordered_on: "ರಂದು ಆದೇಶಿಸಲಾಗಿದೆ",
    issued_by: "ರವರಿಂದ ನೀಡಲ್ಪಟ್ಟಿದೆ",
    order_meds: "ಔಷಧಿಗಳನ್ನು ಆದೇಶಿಸಿ",
    medical_prescription: "ವೈದ್ಯಕೀಯ ಚೀಟಿ",
    reg_no: "ನೋಂದಣಿ ಸಂಖ್ಯೆ",
    patient: "ರೋಗಿ",
    date: "ದಿನಾಂక",
    age: "ವಯಸ್ಸು",
    frequency: "ಆವರ್ತನ",
    duration: "ಅವಧಿ",
    instructions: "ಸೂಚನೆಗಳು",
    doctors_notes: "ವೈದ್ಯರ ಟಿಪ್ಪಣಿಗಳು",
    print: "ಮುದ್ರಿಸು",
    low: "ಕಡಿಮೆ",
    moderate: "ಮಧ್ಯಮ",
    high: "ಹೆಚ್ಚು",
  },
  pa: {
    welcome: "Skrillz ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    select_lang: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    continue: "ਜਾਰੀ ਰੱਖੋ",
    login: "ਸਾਈਨ ਇਨ ਕਰੋ",
    signup: "ਸਾਈਨ ਅੱਪ ਕਰੋ",
    home: "ਹੋਮ",
    appointments: "ਮੁਲਾਕਾਤਾਂ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    request_appointment: "ਮੁਲਾਕਾਤ ਦੀ ਬੇਨਤੀ ਕਰੋ",
    book_now: "ਹੁਣੇ ਬੁੱਕ ਕਰੋ",
    search_doctor: "ਡਾਕਟਰਾਂ ਦੀ ਭਾਲ ਕਰੋ...",
    welcome_back: "ਜੀ ਆਇਆਂ ਨੂੰ",
    login_subtitle: "ਆਪਣੀ ਯਾਤਰਾ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ",
    email_placeholder: "ਆਪਣਾ ਈਮੇਲ ਜਾਂ ਆਈਡੀ ਦਰਜ ਕਰੋ",
    pass_placeholder: "ਆਪਣਾ ਪਾਸਵਰಡ್ ਦਰਜ ਕਰੋ",
    forgot_pass: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    no_account: "ਕੀ ਤੁਹਾਡਾ ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    already_account: "ਪਹਿਲਾਂ ਹੀ ਇੱਕ ਖਾਤਾ ਹੈ?",
    create_account: "ਖਾਤਾ ਬਣਾਓ",
    join_today: "ਅੱਜ ਹੀ SKRILZ ਨਾਲ ਜੁੜੋ",
    personal_info: "ਨਿੱਜੀ ਜਾਣਕਾਰੀ",
    i_am_a: "ਮੈਂ ਇੱਕ... ਹਾਂ",
    doctor_role: "ਡਾਕਟਰ",
    patient_role: "ਮਰੀਜ਼",
    student_role: "ਵਿਦਿਆਰstandardੀ",
    or: "ਜਾਂ",
    continue_with_apple: "Apple ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
    continue_with_google: "Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
    continue_with_linkedin: "LinkedIn ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
    quick_actions: "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
    health_stats: "ਤੁਹਾਡੀ ਸਿਹਤ ਦੇ ਅੰਕੜੇ",
    upcoming_apps: "ਆਉਣ ਵਾਲੀਆਂ ਮੁਲਾਕಾਤਾਂ",
    recommended_docs: "ਸਿਫਾਰਸ਼ ਕੀਤੇ ਡਾਕਟਰ",
    view_details: "ਵੇਰਵੇ ਦੇਖੋ",
    view_all: "ਸਭ ਦੇਖੋ",
    join: "ਸ਼ਾਮਲ ਹੋਵੋ",
    rebook: "ਮੁਲਾਕਾਤ ਦੁਬਾਰਾ ਬੁੱਕ ਕਰੋ",
    medical_essentials: "ਮੈਡੀਕਲ ਜ਼ਰੂਰੀ ਚੀਜ਼ਾਂ",
    total_earning: "ਕੁੱਲ ਕਮਾਈ",
    virtual_clinic: "ਵਰਚੁਅਲ ਕਲੀਨਿਕ",
    earning_potential: "ਕਮਾਈ ਦੀ ਸੰਭਾਵਨਾ",
    professional: "ਪੇਸ਼ੇਵਰ",
    upcoming_meetings: "ਆਉਣ ਵਾਲੀਆਂ ਮੀਟਿੰਗਾਂ",
    pending_reports: "ਬਕਾਇਆ ਮਰੀਜ਼ਾਂ ਦੀਆਂ ਰਿਪੋਰਟਾਂ",
    open_records: "ਰਿਕਾਰਡ ਖੋਲ੍ਹੋ",
    review: "ਸਮੀਖਿਆ ਕਰੋ",
    my_appointments: "ਮੇਰੀਆਂ ਮੁਲਾਕਾਤਾਂ",
    upcoming: "ਆਉਣ ਵਾਲੀਆਂ",
    history: "ਇਤਿਹਾਸ",
    accepted: "ਪ੍ਰਵਾਨਿਤ",
    suggested: "ਸੁਝਾਏ ਗਏ",
    confirm_time: "ਸਮੇਂ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    select_date: "ਮਿਤੀ ਚੁਣੋ",
    reason: "ਆਉਣ ਦਾ ਕਾਰਨ",
    status_pending: "ਬਕਾਇਆ",
    status_accepted: "ਸਵੀਕਾਰ ਕੀਤਾ",
    status_cancelled: "ਰੱਦ ਕੀਤਾ",
    messages: "ਸੁਨੇਹੇ",
    type_message: "ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...",
    online: "ਆਨਲਾਈਨ",
    offline: "ਆਫਲਾਈਨ",
    start_call: "ਕਾਲ ਸ਼ੁਰੂ ਕਰੋ",
    end_call: "ਕਾਲ ਖਤਮ ਕਰੋ",
    mute: "ਮਿਊਟ",
    video_on: "ਵੀਡੀਓ ਚਾਲੂ",
    video_off: "ਵੀਡੀਓ ਬੰਦ",
    health_status: "ਸਿਹਤ ਸਥਿਤੀ",
    medical_records: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
    prescriptions: "ਨੁਸਖੇ",
    recommended_doctors: "ਸਿਫਾਰਸ਼ ਕੀਤੇ ਡਾਕਟਰ",
    contact_support: "ਸਹਾਇਤਾ ਲਈ ਸੰਪਰਕ ਕਰੋ",
    change_language: "ਭਾਸ਼ਾ ਬਦਲੋ",
    choose_doctor_date: "ਡਾਕਟਰ ਅਤੇ ਮਿਤੀ ਚੁਣੋ",
    select_doctor: "ਡਾਕਟਰ ਚੁਣੋ",
    consult_type: "ਸਲਾਹ-ਮਸ਼ਵਰੇ ਦੀ ਕਿਸਮ",
    video_call: "ਵੀਡੀਓ ਕਾਲ",
    audio_call: "ਆਡੀਓ ਕਾਲ",
    clinic_visit: "ਕਲੀਨਿਕ ਵਿਜ਼ਿਟ",
    payment_summary: "ਭੁਗਤਾਨ ਦਾ ਸਾਰ",
    consult_fee: "ਸਲਾਹ-ਮਸ਼ਵਰਾ ਫੀਸ",
    platform_charges: "ਪਲੇਟਫਾਰਮ ਖਰਚੇ",
    total_payable: "ਕੁੱਲ ਦੇਣਯੋਗ",
    all_appointments: "ਸਾਰੀਆਂ ਮੁਲਾਕਾਤਾਂ",
    manage_schedule: "ਆਪਣੇ ਸਲਾਹ-ਮਸ਼ਵਰੇ ਦੇ ਕਾਰਜਕ੍ਰਮ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ",
    search_patient: "ਮਰੀਜ਼ ਦਾ ਨਾਮ ਖੋਜੋ...",
    select_time_title: "ਸਲਾਹ-ਮਸ਼ਵਰੇ ਦਾ ਸਮਾਂ ਚੁਣੋ:",
    accept_set_time: "ਸਵੀਕਾਰ ਕਰੋ ਅਤੇ ਸਮਾਂ ਨਿਰਧಾರਤ ਕਰੋ",
    view_report: "ਰਿਪੋਰਟ ਦੇਖੋ",
    no_apps_found: "ਕੋਈ ਮੁਲਾਕਾਤ ਨਹੀਂ ਮਿਲੀ",
    search_patient_msg: "ਮਰੀਜ਼ ਜਾਂ ਸੰਦੇਸ਼ ਦੀ ਖੋਜ ਕਰੋ...",
    search_doctor_msg: "ਡਾਕਟਰ ਜਾਂ ਸੰਦੇਸ਼ ਦੀ ਖੋਜ ਕਰੋ...",
    active_now: "ਹੁਣੇ ਸਰਗਰਮ",
    patient_history: "ਮਰੀਜ਼ ਦਾ ਇਤਿਹਾਸ",
    upload_prescription_report: "ਪ੍ਰਕਾਸ਼ਨ / ਰਿਪੋਰਟ ਅਪਲੋਡ ਕਰੋ",
    health_profile: "ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ",
    manage_health_info: "ਆਪਣੀ ਨਿੱਜੀ ਸਿਹਤ ਜਾਣਕਾਰੀ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ",
    basic_info: "ਬੁਨਿਆਦੀ ਜਾਣਕਾਰੀ",
    height: "ਕੱਦ (cm)",
    weight: "ਭਾਰ (kg)",
    blood_group: "ਖੂਨ ਦਾ ਗਰੁੱਪ",
    medical_history: "ਡਾਕਟਰੀ ਇਤਿਹਾਸ",
    existing_conditions: "ਮੌਜੂਦਾ ਸਥਿਤੀਆਂ (ਜਿਵੇਂ ਕਿ ਦਿਲ ਦਾ ਦੌਰਾ, ਸ਼ੂਗਰ)",
    past_surgeries: "ਪਿਛਲੀਆਂ ਸਰਜਰੀਆਂ / ਹਸਪਤਾਲ ਵਿੱਚ ਭਰਤੀ",
    lifestyle: "ਜੀਵਨਸ਼ੈਲੀ",
    save_profile: "ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    upload_manage_health: "ਆਪਣੇ ਸਿਹਤ ਦਸਤਾਵੇਜ਼ ਅਪਲોਡ ਅਤੇ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
    uploaded_by: "ਦੁਆਰਾ ਅਪਲೋਡ ਕੀਤਾ ਗਿਆ",
    view: "ਦੇਖੋ",
    download: "ਡਾਊਨਲੋਡ ਕਰੋ",
    delete: "ਮਿਟਾਓ",
    choose_action: "ਕੋਈ ਕਾਰਵਾਈ ਚੁਣੋ",
    upload_pdf_img: "PDF / ਚਿੱਤਰ ਅਪਲੋਡ ਕਰੋ",
    camera_scan: "ਕੈਮਰਾ (ਸਕੈਨ)",
    active_medications: "ਸਰਗਰਮ ਦਵਾਈਆਂ",
    prescription_history: "ਨੁਸਖ਼ਾ ਇਤਿਹਾਸ",
    dr_dosage: "ਡਾਕਟਰ / ਖੁਰਾਕ",
    instruction: "ਹਦਾਇਤ",
    ordered_on: "ਨੂੰ ਆਰਡਰ ਕੀਤਾ ਗਿਆ",
    issued_by: "ਦੁਆਰਾ ਜਾਰੀ ਕੀਤਾ ਗਿਆ",
    order_meds: "ਦਵਾਈਆਂ ਆਰਡਰ ਕਰੋ",
    medical_prescription: "ਡਾਕਟری ਨੁਸਖ਼ਾ",
    reg_no: "ਰਜਿਸਟਰ ਨੰਬਰ",
    patient: "ਮਰੀਜ਼",
    date: "ਤਾਰੀਖ",
    age: "ਉਮਰ",
    frequency: "ਵਾਰਵਾਰਤਾ",
    duration: "ਮਿਆਦ",
    instructions: "ਹਦਾਇਤਾਂ",
    doctors_notes: "ਡਾਕਟਰ ਦੇ ਨੋਟਸ",
    print: "ਪ੍ਰਿੰਟ ਕਰੋ",
    low: "ਘੱਟ",
    moderate: "ਦਰਮਿਆਨਾ",
    high: "ਉੱਚ",
  },
  ta: {
    welcome: "Skrillz-க்கு வரவேற்கிறோம்",
    select_lang: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    continue: "தொடரவும்",
    login: "உள்நுழைக",
    signup: "பதிவு செய்க",
    home: "முகப்பு",
    appointments: "சந்திப்புகள்",
    profile: "சுயவிவரம்",
    request_appointment: "சந்திப்பைக் கோருங்கள்",
    book_now: "இப்போதே பதிவு செய்யுங்கள்",
    search_doctor: "மருத்துவர்களைத் தேடுங்கள்...",
    welcome_back: "மீண்டும் வருக",
    login_subtitle: "உங்கள் பயணத்தைத் தொடர உள்நுழைக",
    email_placeholder: "ನಿಮ್ಮ மின்னஞ்சல் அல்லது ஐடியை உள்ளிடவும்",
    pass_placeholder: "உங்கள் கடவுச்சೊல்லை உள்ளிடவும்",
    forgot_pass: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    no_account: "கணக்கு இல்லையா?",
    already_account: "ஏற்கனவே கணக்கு உள்ளதா?",
    create_account: "கணக்கை உருவாக்கு",
    join_today: "இன்றே SKRILZ-ல் இணையுங்கள்",
    personal_info: "தனிப்பட்ட தகவல்",
    i_am_a: "நான் ஒரு...",
    doctor_role: "மருத்துவர்",
    patient_role: "நோயாளி",
    student_role: "மாணவர்",
    or: "அல்லது",
    continue_with_apple: "Apple உடன் தொடரவும்",
    continue_with_google: "Google உடன் தொடரவும்",
    continue_with_linkedin: "LinkedIn உடன் தொடரவும்",
    quick_actions: "விரைவான செயல்கள்",
    health_stats: "உங்கள் சுகாதார புள்ளிவிவரங்கள்",
    upcoming_apps: "வரவிருக்கும் சந்திப்புகள்",
    recommended_docs: "பரிந்துரைக்கப்பட்ட மருத்துவர்கள்",
    view_details: "விவரங்களைக் காண்க",
    view_all: "அனைத்தையும் காண்க",
    join: "இணையுங்கள்",
    rebook: "மீண்டும் முன்பதிவு செய்யுங்கள்",
    medical_essentials: "மருத்துவ அத்தியாவசியங்கள்",
    total_earning: "மொத்த வருவாய்",
    virtual_clinic: "மெய்நிகர் கிளினிக்",
    earning_potential: "வருவாய் திறன்",
    professional: "தொழில்முறை",
    upcoming_meetings: "வரவிருக்கும் கூட்டங்கள்",
    pending_reports: "நிலுவையில் உள்ள நோயாளி அறிக்கைகள்",
    open_records: "பதிவுகளைத் திறக்கவும்",
    review: "மதிப்பாய்வு செய்க",
    my_appointments: "எனது சந்திப்புகள்",
    upcoming: "வரவிருப்பவை",
    history: "வரலாறு",
    accepted: "ஏற்றுக்கொள்ளப்பட்டது",
    suggested: "பரிந்துரைக்கப்பட்டது",
    confirm_time: "நேரத்தை உறுதிப்படுத்தவும்",
    select_date: "தேதியைத் தேர்ந்தெடுக்கவும்",
    reason: "வருகைக்கான காரணம்",
    status_pending: "நிலுவையில் உள்ளது",
    status_accepted: "ஏற்றுக்கொள்ளப்பட்டது",
    status_cancelled: "ரத்து செய்யப்பட்டது",
    messages: "செய்திகள்",
    type_message: "செய்தியைத் தட்டச்சு செய்க...",
    online: "ஆன்லைன்",
    offline: "ஆஃப்லைன்",
    start_call: "அழைப்பைத் தொடங்கவும்",
    end_call: "அழைப்பை முடிக்கவும்",
    mute: "அமைதி",
    video_on: "வீடியோ ஆன்",
    video_off: "வீடியோ ஆஃப்",
    health_status: "சுகாதார நிலை",
    medical_records: "மருத்துவ பதிவுகள்",
    prescriptions: "மருந்துச் சீட்டுகள்",
    recommended_doctors: "பரிந்துரைக்கப்பட்ட மருத்துவர்கள்",
    contact_support: "ஆதரவைத் தொடர்பு கொள்ளவும்",
    change_language: "மொழியை மாற்றவும்",
    choose_doctor_date: "மருத்துவர் மற்றும் தேதியைத் தேர்ந்தெடுக்கவும்",
    select_doctor: "மருத்துவரைத் தேர்ந்தெடுக்கவும்",
    consult_type: "ஆலோசனை வகை",
    video_call: "வீடியோ அழைப்பு",
    audio_call: "ஆடியோ அழைப்பு",
    clinic_visit: "கிளினிக் வருகை",
    payment_summary: "கட்டணச் சுருக்கம்",
    consult_fee: "ஆலோசனை கட்டணம்",
    platform_charges: "பிளாட்பார்ம் கட்டணங்கள்",
    total_payable: "மொத்தம் செலுத்த வேண்டியது",
    all_appointments: "அனைத்து சந்திப்புகள்",
    manage_schedule: "உங்கள் ஆலோசனை அட்டவணையை நிர்வகிக்கவும்",
    search_patient: "நோயாளி பெயரைத் தேடுங்கள்...",
    select_time_title: "ஆலோசனை நேரத்தைத் தேர்ந்தெடுக்கவும்:",
    accept_set_time: "ஏற்றுக்கொண்டு நேரத்தை நிர்ணயிக்கவும்",
    view_report: "அறிக்கையைப் பார்க்கவும்",
    no_apps_found: "சந்திப்புகள் எதுவும் இல்லை",
    search_patient_msg: "நோயாளி அல்லது செய்தியைத் தேடுங்கள்...",
    search_doctor_msg: "மருத்துவர் அல்லது செய்தியைத் தேடுங்கள்...",
    active_now: "தற்போது செயலில் உள்ளது",
    patient_history: "நோயாளி வரலாறு",
    upload_prescription_report: "மருந்துச் சீட்டு / அறிக்கையைப் பதிவேற்றவும்",
    health_profile: "சுகாதார விவரக்குறிப்பு",
    manage_health_info: "உங்கள் தனிப்பட்ட சுகாதாரத் தகவலை நிர்வகிக்கவும்",
    basic_info: "அடிப்படை தகவல்",
    height: "உயரம் (cm)",
    weight: "எடை (kg)",
    blood_group: "இரத்த வகை",
    medical_history: "மருத்துவ வரலாறு",
    existing_conditions: "தற்போதுள்ள நிலைமைகள் (எ.கா. மாரடைப்பு, நீரிழிவு)",
    past_surgeries: "கடந்த கால அறுவை சிகிச்சைகள் / மருத்துவமனையில் அனுமதிக்கப்பட்டவை",
    lifestyle: "வாழ்க்கை முறை",
    save_profile: "சுகாதார விவரக்குறிப்பைச் சேமிக்கவும்",
    upload_manage_health: "உங்கள் சுகாதார ஆவணங்களைப் பதிவேற்றவும் மற்றும் நிர்வகிக்கவும்",
    uploaded_by: "இவரால் பதிவேற்றப்பட்டது",
    view: "காண்க",
    download: "பதிவிறக்கு",
    delete: "நீக்கு",
    choose_action: "ஒரு செயலைத் தேர்ந்தெடுக்கவும்",
    upload_pdf_img: "PDF / படத்தைப் பதிவேற்றவும்",
    camera_scan: "கேமரா (ஸ்கேன்)",
    active_medications: "செயலில் உள்ள மருந்துகள்",
    prescription_history: "மருந்துச் சீட்டு வரலாறு",
    dr_dosage: "டாக்டர் / அளவு",
    instruction: "அறிவுறுத்தல்",
    ordered_on: "அன்று ஆர்டர் செய்யப்பட்டது",
    issued_by: "இவரால் வழங்கப்பட்டது",
    order_meds: "மருந்துகளை ஆர்டர் செய்யுங்கள்",
    medical_prescription: "மருத்துவச் சீட்டு",
    reg_no: "பதிவு எண்",
    patient: "நோயாளி",
    date: "தேதி",
    age: "வயது",
    frequency: "அதிர்வெண்",
    duration: "காலம்",
    instructions: "அறிவுறுத்தல்கள்",
    doctors_notes: "மருத்துவரின் குறிப்புகள்",
    print: "அச்சிடுக",
    low: "குறைவு",
    moderate: "மிதமான",
    high: "அதிகம்",
  },
  te: {
    welcome: "Skrillz కి స్వాగతం",
    select_lang: "మీ భాషను ఎంచుకోండి",
    continue: "కొనసాగించండి",
    login: "సైన్ ఇన్",
    signup: "సైన్ అప్",
    home: "హోమ్",
    appointments: "అపాయింట్‌మెంట్‌లు",
    profile: "ప్రొఫైల్",
    request_appointment: "అపాయింట్‌మెంట్ కోసం అభ్యర్థించండి",
    book_now: "ఇప్పుడే బుక్ చేయండి",
    search_doctor: "వైద్యుల కోసం వెతకండి...",
    welcome_back: "తిరిగి స్వాగతం",
    login_subtitle: "మీ ప్రయాణాన్ని కొనసాగించడానికి సైన్ ఇన్ చేయండి",
    email_placeholder: "మీ ఇమెయిల్ లేదా ఐడిని నమోదు చేయండి",
    pass_placeholder: "మీ పాస్‌వర్డ్ నమోదు చేయండి",
    forgot_pass: "పాస్‌వర్డ్ మర్చిపోయారా?",
    no_account: "ఖాతా లేదా?",
    already_account: "ఇప్పటికే ఖాతా ఉందా?",
    create_account: "ఖాతాను సృష్టించండి",
    join_today: "ఈరోజే SKRILZ లో చేరండి",
    personal_info: "వ్యక్తిగత సమాచారం",
    i_am_a: "నేను ఒక...",
    doctor_role: "వైద్యుడు",
    patient_role: "రోగి",
    student_role: "విద్యార్థి",
    or: "లేదా",
    continue_with_apple: "Apple తో కొనసాగండి",
    continue_with_google: "Google తో కొనసాగండి",
    continue_with_linkedin: "LinkedIn తో కొనసాగండి",
    quick_actions: "త్వరిత చర్యలు",
    health_stats: "మీ ఆరోగ్య గణాంకాలు",
    upcoming_apps: "రాబోయే అపాయింట్‌మెంట్‌లు",
    recommended_docs: "సిఫార్సు చేయబడిన వైద్యులు",
    view_details: "వివరాలను చూడండి",
    view_all: "అన్నీ చూడండి",
    join: "చేరండి",
    rebook: "అపాయింట్‌మెంట్‌ను మళ్లీ బుక్ చేయండి",
    medical_essentials: "వైద్య అవసరాలు",
    total_earning: "మొత్తం సంపాదన",
    virtual_clinic: "వర్చువల్ క్లినిక్",
    earning_potential: "సంపాదన సంభావ్యత",
    professional: "వృత్తిపరమైన",
    upcoming_meetings: "రాబోయే సమావేశాలు",
    pending_reports: "పెండింగ్‌లో ఉన్న రోగి నివేదికలు",
    open_records: "రికార్డులను తెరవండి",
    review: "समीक्षाించండి",
    my_appointments: "నా అపాయింట్‌మెంట్‌లు",
    upcoming: "రాబోయేవి",
    history: "చరిత్ర",
    accepted: "ఆమోదించబడింది",
    suggested: "సూచించబడింది",
    confirm_time: "సమయాన్ని నిర్ధారించండి",
    select_date: "తేదీని ఎంచుకోండి",
    reason: "సందర్శన కారణం",
    status_pending: "పెండింగ్‌లో ఉంది",
    status_accepted: "ఆమోదించబడింది",
    status_cancelled: "రద్దు చేయబడింది",
    messages: "సందేశాలు",
    type_message: "సందేశాన్ని టైప్ చేయండి...",
    online: "ఆన్‌లైన్",
    offline: "ఆఫ్‌లైన్",
    start_call: "కాల్ ప్రారంభించండి",
    end_call: "కాల్ ముగించండి",
    mute: "మ్యూట్",
    video_on: "వీడియో ఆన్",
    video_off: "వీడియో ఆఫ్",
    health_status: "ఆరోగ్య స్థితి",
    medical_records: "వైద్య కోడ్లు",
    prescriptions: "మందుల చీటిలు",
    recommended_doctors: "సిఫార్సు చేయబడిన వైద్యులు",
    contact_support: "మద్దతును సంప్రదించండి",
    change_language: "భాషను మార్చండి",
    choose_doctor_date: "వైద్యుడిని మరియు తేదీని ఎంచుకోండి",
    select_doctor: "వైద్యుడిని ఎంచుకోండి",
    consult_type: "సంప్రదింపు రకం",
    video_call: "వీడియో కాల్",
    audio_call: "ఆడియో కాల్",
    clinic_visit: "క్లినిక్ సందర్శన",
    payment_summary: "చెల్లింపు సారాంశం",
    consult_fee: "సంప్రదింపు రుసుము",
    platform_charges: "ప్లాట్‌ఫారమ్ ఛార్జీలు",
    total_payable: "మొత్తం చెల్లించవలసినది",
    all_appointments: "అన్ని అపాయింట్‌మెంట్‌లు",
    manage_schedule: "మీ సంప్రదింపు షెడ్యూల్‌ను నిర్వహించండి",
    search_patient: "రోగి పేరు కోసం వెతకండి...",
    select_time_title: "సంప్రదింపు సమయాన్ని ఎంచుకోండి:",
    accept_set_time: "ఆమోదించండి మరియు సమయాన్ని నిర్ణయించండి",
    view_report: "నివేదికను చూడండి",
    no_apps_found: "అపాయింట్‌మెంట్‌లు ఏవీ లేవు",
    search_patient_msg: "రోగి లేదా సందేశం కోసం వెతకండి...",
    search_doctor_msg: "వైద్యుడు లేదా సందేశం కోసం వెతకండి...",
    active_now: "ప్రస్తుతం అందుబాటులో ఉంది",
    patient_history: "రోగి చరిత్ర",
    upload_prescription_report: "ప్రిస్క్రిప్షన్ / రిపోర్ట్ అప్‌లోడ్ చేయండి",
    health_profile: "ఆరోగ్య ప్రొఫైల్",
    manage_health_info: "మీ వ్యక్తిగత ఆరోగ్య సమాచారాన్ని నిర్వహించండి",
    basic_info: "ప్రాథమిక సమాచారం",
    height: "ఎత్తు (cm)",
    weight: "బరువు (kg)",
    blood_group: "రక్త వర్గం",
    medical_history: "వైద్య చరిత్ర",
    existing_conditions: "ఇప్పటికే ఉన్న పరిస్థితులు (ఉదా. గుండెపోటు, మధుమేహం)",
    past_surgeries: "గత శస్త్రచికిత్సలు / ఆస్పత్రిలో చేరడం",
    lifestyle: "జీవనశైలి",
    save_profile: "ఆరోగ్య ప్రొఫైల్‌ను సేవ్ చేయండి",
    upload_manage_health: "మీ ఆరోగ్య పత్రాలను అప్‌లోడ్ చేయండి మరియు నిర్వహించండి",
    uploaded_by: "వీరిచే అప్‌లోడ్ చేయబడింది",
    view: "చూడండి",
    download: "డೌన్‌లోడ్ చేయండి",
    delete: "తొలగించు",
    choose_action: "ఒక చర్యను ఎంచుకోండి",
    upload_pdf_img: "PDF / చిత్రాన్ని అప్‌లోడ్ చేయండి",
    camera_scan: "కెమెరా (స్కాన్)",
    active_medications: "చురుకైన మందులు",
    prescription_history: "మందుల చీటి చరిత్ర",
    dr_dosage: "వైద్యుడు / మోతాదు",
    instruction: "సూచన",
    ordered_on: "నాడు ఆర్డర్ చేయబడింది",
    issued_by: "వీరిచే జారీ చేయబడింది",
    order_meds: "మందులను ఆర్డర్ చేయండి",
    medical_prescription: "వైద్య సలహా పత్రం",
    reg_no: "రిజిస్ట్రేషన్ సంఖ్య",
    patient: "రోగి",
    date: "తేదీ",
    age: "వయస్సు",
    frequency: "ఫ్రీక్వెన్సీ",
    duration: "వ్యవధి",
    instructions: "సూచనలు",
    doctors_notes: "వైద్యుని గమనికలు",
    print: "ప్రింట్ చేయండి",
    low: "తక్కువ",
    moderate: "మితమైన",
    high: "ఎక్కువ",
  },
  es: {
    welcome: "Bienvenido a Skrillz",
    select_lang: "Selecciona tu idioma",
    continue: "Continuar",
    login: "Iniciar sesión",
    signup: "Registrarse",
    home: "Inicio",
    appointments: "Citas",
    profile: "Perfil",
    request_appointment: "Solicitar Cita",
    book_now: "Reservar Ahora",
    search_doctor: "Buscar doctores...",
    welcome_back: "Bienvenido de nuevo",
    login_subtitle: "Inicia sesión para continuar tu viaje",
    email_placeholder: "Ingresa tu correo o ID",
    pass_placeholder: "Ingresa tu contraseña",
    forgot_pass: "¿Olvidaste tu contraseña?",
    no_account: "¿No tienes una cuenta?",
    already_account: "¿Ya tienes una cuenta?",
    create_account: "Crear Cuenta",
    join_today: "Únete a SKRILZ hoy",
    personal_info: "Información Personal",
    i_am_a: "Soy un...",
    doctor_role: "Doctor",
    patient_role: "Paciente",
    student_role: "Estudiante",
    or: "O",
    continue_with_apple: "Continuar con Apple",
    continue_with_google: "Continuar con Google",
    continue_with_linkedin: "Continuar con LinkedIn",
    quick_actions: "Acciones Rápidas",
    health_stats: "Tus Estadísticas de Salud",
    upcoming_apps: "Próximas Citas",
    recommended_docs: "Doctores Recomendados",
    view_details: "Ver Detalles",
    view_all: "Ver Todo",
    join: "Unirse",
    rebook: "Re-reservar Cita",
    medical_essentials: "Esenciales Médicos",
    total_earning: "Ganancia Total",
    virtual_clinic: "Clínica Virtual",
    earning_potential: "Potencial de Ganancia",
    professional: "Profesional",
    upcoming_meetings: "Próximas Reuniones",
    pending_reports: "Informes de Pacientes Pendientes",
    open_records: "Abrir Récords",
    review: "Revisar",
    my_appointments: "Mis Citas",
    upcoming: "Próximas",
    history: "Historial",
    accepted: "Aceptadas",
    suggested: "Sugeridas",
    confirm_time: "Confirmar Hora",
    select_date: "Seleccionar Fecha",
    reason: "Motivo de la visita",
    status_pending: "Pendiente",
    status_accepted: "Aceptada",
    status_cancelled: "Cancelada",
    messages: "Mensajes",
    type_message: "Escribe un mensaje...",
    online: "En línea",
    offline: "Desconectado",
    start_call: "Iniciar Llamada",
    end_call: "Finalizar Llamada",
    mute: "Silenciar",
    video_on: "Video Activado",
    video_off: "Video Desactivado",
    health_status: "Estado de Salud",
    medical_records: "Récords Médicos",
    prescriptions: "Recetas",
    recommended_doctors: "Doctores Recomendados",
    contact_support: "Contactar Soporte",
    change_language: "Cambiar Idioma",
    choose_doctor_date: "Elegir doctor y fecha",
    select_doctor: "Seleccionar Doctor",
    consult_type: "Tipo de Consulta",
    video_call: "Videollamada",
    audio_call: "Llamada de Audio",
    clinic_visit: "Visita a la Clínica",
    payment_summary: "Resumen de Pago",
    consult_fee: "Tarifa de Consulta",
    platform_charges: "Cargos de la Plataforma",
    total_payable: "Total a Pagar",
    all_appointments: "Todas las Citas",
    manage_schedule: "Administra tu horario de consulta",
    search_patient: "Buscar nombre del paciente...",
    select_time_title: "Seleccionar Hora de Consulta:",
    accept_set_time: "Aceptar y Programar",
    view_report: "Ver Informe",
    no_apps_found: "No se encontraron citas",
    search_patient_msg: "Buscar paciente o mensaje...",
    search_doctor_msg: "Buscar doctor o mensaje...",
    active_now: "Activo Ahora",
    patient_history: "Historial del Paciente",
    upload_prescription_report: "Subir Receta / Informe",
    health_profile: "Perfil de Salud",
    manage_health_info: "Gestiona tu información de salud personal",
    basic_info: "Información Básica",
    height: "Altura (cm)",
    weight: "Peso (kg)",
    blood_group: "Grupo Sanguíneo",
    medical_history: "Historial Médico",
    existing_conditions: "Condiciones Existentes (ej. ataque cardíaco, diabetes)",
    past_surgeries: "Cirugías Pasadas / Hospitalizaciones",
    lifestyle: "Estilo de Vida",
    save_profile: "Guardar Perfil de Salud",
    upload_manage_health: "Carga y gestiona tus documentos de salud",
    uploaded_by: "Subido por",
    view: "Ver",
    download: "Descargar",
    delete: "Eliminar",
    choose_action: "Elige una acción",
    upload_pdf_img: "Subir PDF / Imagen",
    camera_scan: "Cámara (Escanear)",
    active_medications: "Medicamentos Activos",
    prescription_history: "Historial de Recetas",
    dr_dosage: "Dr. / Dosis",
    instruction: "Instrucción",
    ordered_on: "Pedido el",
    issued_by: "Emitido por",
    order_meds: "Pedir Medicamentos",
    medical_prescription: "Prescripción Médica",
    reg_no: "Núm. Registro",
    patient: "Paciente",
    date: "Fecha",
    age: "Edad",
    frequency: "Frecuencia",
    duration: "Duración",
    instructions: "Instrucciones",
    doctors_notes: "Notas del Doctor",
    print: "Imprimir",
    low: "Bajo",
    moderate: "Moderado",
    high: "Alto",
  },
  zh: {
    welcome: "欢迎来到 Skrillz",
    select_lang: "选择您的语言",
    continue: "继续",
    login: "登录",
    signup: "注册",
    home: "主页",
    appointments: "预约",
    profile: "个人资料",
    request_appointment: "请求预约",
    book_now: "立即预订",
    search_doctor: "寻找医生...",
    welcome_back: "欢迎回来",
    login_subtitle: "登录以继续您的旅程",
    email_placeholder: "输入您的电子邮件或ID",
    pass_placeholder: "输入您的密码",
    forgot_pass: "忘记密码？",
    no_account: "还没有账号？",
    already_account: "已有账号？",
    create_account: "创建账号",
    join_today: "立即加入 SKRILZ",
    personal_info: "个人信息",
    i_am_a: "我是一名...",
    doctor_role: "医生",
    patient_role: "患者",
    student_role: "学生",
    or: "或",
    continue_with_apple: "使用 Apple 继续",
    continue_with_google: "使用 Google 继续",
    continue_with_linkedin: "使用 LinkedIn 继续",
    quick_actions: "快速操作",
    health_stats: "您的健康统计",
    upcoming_apps: "近期预约",
    recommended_docs: "推荐医生",
    view_details: "查看详情",
    view_all: "查看全部",
    join: "加入",
    rebook: "重新预约",
    medical_essentials: "医疗必需品",
    total_earning: "总收入",
    virtual_clinic: "虚拟诊所",
    earning_potential: "收入潜力",
    professional: "专业信息",
    upcoming_meetings: "近期会议",
    pending_reports: "待处理患者报告",
    open_records: "打开记录",
    review: "审查",
    my_appointments: "我的预约",
    upcoming: "即将到来",
    history: "历史记录",
    accepted: "已接受",
    suggested: "已建议",
    confirm_time: "确认时间",
    select_date: "选择日期",
    reason: "就诊原因",
    status_pending: "待处理",
    status_accepted: "已接受",
    status_cancelled: "已取消",
    messages: "消息",
    type_message: "输入消息...",
    online: "在线",
    offline: "离线",
    start_call: "开始通话",
    end_call: "结束通话",
    mute: "静音",
    video_on: "视频开启",
    video_off: "视频关闭",
    health_status: "健康状况",
    medical_records: "医疗记录",
    prescriptions: "处方",
    recommended_doctors: "推荐医生",
    contact_support: "联系支持",
    change_language: "更改语言",
    choose_doctor_date: "选择医生和日期",
    select_doctor: "选择医生",
    consult_type: "咨询类型",
    video_call: "视频通话",
    audio_call: "语音通话",
    clinic_visit: "诊所就诊",
    payment_summary: "付款摘要",
    consult_fee: "咨询费",
    platform_charges: "平台费",
    total_payable: "总应付金额",
    all_appointments: "所有预约",
    manage_schedule: "管理您的咨询安排",
    search_patient: "搜索患者姓名...",
    select_time_title: "选择咨询时间：",
    accept_set_time: "接受并设置时间",
    view_report: "查看报告",
    no_apps_found: "未找到预约",
    search_patient_msg: "搜索患者或信息...",
    search_doctor_msg: "搜索医生或信息...",
    active_now: "现在活跃",
    patient_history: "患者病史",
    upload_prescription_report: "上传处方/报告",
    health_profile: "健康档案",
    manage_health_info: "管理您的个人健康信息",
    basic_info: "基本信息",
    height: "身高 (cm)",
    weight: "体重 (kg)",
    blood_group: "血型",
    medical_history: "病史",
    existing_conditions: "现有病情（如心脏病、糖尿病）",
    past_surgeries: "过往手术/住院史",
    lifestyle: "生活方式",
    save_profile: "保存健康档案",
    upload_manage_health: "上传并管理您的健康文档",
    uploaded_by: "上传者：",
    view: "查看",
    download: "下载",
    delete: "删除",
    choose_action: "选择操作",
    upload_pdf_img: "上传 PDF / 图片",
    camera_scan: "相机 (扫描)",
    active_medications: "正在服用的药物",
    prescription_history: "处方历史",
    dr_dosage: "医生 / 剂量",
    instruction: "说明",
    ordered_on: "订购于",
    issued_by: "发布者：",
    order_meds: "订购药物",
    medical_prescription: "医疗处方",
    reg_no: "注册号",
    patient: "患者",
    date: "日期",
    age: "年龄",
    frequency: "频率",
    duration: "时长",
    instructions: "说明",
    doctors_notes: "医生笔记",
    print: "打印",
    low: "低",
    moderate: "适中",
    high: "高",
  },
  ur: {
    welcome: "Skrillz میں خوش آمدید",
    select_lang: "اپنی زبان منتخب کریں",
    continue: "جاری رکھیں",
    login: "سائن ان",
    signup: "سائن اپ",
    home: "ہوم",
    appointments: "اپائنٹمنٹ",
    profile: "پروفائل",
    request_appointment: "اپائنٹمنٹ کی درخواست کریں",
    book_now: "ابھی بک کریں",
    search_doctor: "ڈاکٹروں کو تلاش کریں...",
    welcome_back: "خوش آمدید",
    login_subtitle: "اپنا سفر جاری رکھنے کے لیے سائن ان کریں",
    email_placeholder: "اپنا ای میل یا آئی ڈی درج کریں",
    pass_placeholder: "اپنا پاس ورڈ درج کریں",
    forgot_pass: "پاس ورڈ بھول گئے؟",
    no_account: "کیا آپ کا اکاؤنٹ نہیں ہے؟",
    already_account: "پہلے سے ہی اکاؤنٹ ہے؟",
    create_account: "اکاؤنٹ بنائیں",
    join_today: "آج ہی SKRILZ میں شامل ہوں",
    personal_info: "ذاتی معلومات",
    i_am_a: "میں ایک... ہوں",
    doctor_role: "ڈاکٹر",
    patient_role: "مریض",
    student_role: "طالب علم",
    or: "یا",
    continue_with_apple: "Apple کے ساتھ جاری رکھیں",
    continue_with_google: "Google کے ساتھ جاری رکھیں",
    continue_with_linkedin: "LinkedIn کے ساتھ جاری رکھیں",
    quick_actions: "فوری کارروائیاں",
    health_stats: "آپ کے صحت کے اعداد و شمار",
    upcoming_apps: "آئندہ اپائنٹمنٹس",
    recommended_docs: "تجویز کردہ ڈاکٹر",
    view_details: "تفصیلات دیکھیں",
    view_all: "سب دیکھیں",
    join: "شامل ہوں",
    rebook: "دوبارہ اپائنٹمنٹ بک کریں",
    medical_essentials: "طبی ضروریات",
    total_earning: "کل آمدنی",
    virtual_clinic: "ورچوئل کلینک",
    earning_potential: "آمدنی کی صلاحیت",
    professional: "پیشہ ورانہ",
    upcoming_meetings: "آئندہ ملاقاتیں",
    pending_reports: "زیر التواء مریضوں کی رپورٹیں",
    open_records: "ریکارڈ کھولیں",
    review: "جائزہ لیں",
    my_appointments: "میری اپائنٹمنٹس",
    upcoming: "آئندہ",
    history: "تاریخ",
    accepted: "قبول شدہ",
    suggested: "تجویز کردہ",
    confirm_time: "وقت کی تصدیق کریں",
    select_date: "تاریخ منتخب کریں",
    reason: "دورے کی وجہ",
    status_pending: "زیر التواء",
    status_accepted: "قبول شدہ",
    status_cancelled: "منسوخ شدہ",
    messages: "پیغامات",
    type_message: "پیغام لکھیں...",
    online: "آن لائن",
    offline: "آف لائن",
    start_call: "کال شروع کریں",
    end_call: "کال ختم کریں",
    mute: "خاموش",
    video_on: "ویڈیو آن",
    video_off: "ویڈیو آف",
    health_status: "صحت کی حالت",
    medical_records: "طبی ریکارڈ",
    prescriptions: "نسخے",
    recommended_doctors: "تجویز کردہ ڈاکٹر",
    contact_support: "سپورٹ سے رابطہ کریں",
    change_language: "زبان تبدیل کریں",
    choose_doctor_date: "ڈاکٹر اور تاریخ منتخب کریں",
    select_doctor: "ڈاکٹر منتخب کریں",
    consult_type: "مشورے کی قسم",
    video_call: "ویڈیو کال",
    audio_call: "آڈیو کال",
    clinic_visit: "کلینک کا دورہ",
    payment_summary: "ادائیگی کا خلاصہ",
    consult_fee: "مشورہ فیس",
    platform_charges: "پلیٹ فارم چارجز",
    total_payable: "کل قابل ادائیگی",
    all_appointments: "تمام اپائنٹمنٹس",
    manage_schedule: "اپنے مشورے کے شیڈول کا نظم کریں",
    search_patient: "مریض کا نام تلاش کریں...",
    select_time_title: "مشورے کا وقت منتخب کریں:",
    accept_set_time: "قبول کریں اور وقت مقرر کریں",
    view_report: "رپورٹ دیکھیں",
    no_apps_found: "کوئی اپائنٹمنٹ نہیں ملی",
    search_patient_msg: "مریض یا پیغام تلاش کریں...",
    search_doctor_msg: "ڈاکٹر یا پیغام تلاش کریں...",
    active_now: "ابھی فعال",
    patient_history: "مریض کی ہسٹری",
    upload_prescription_report: "نسخہ یا رپورٹ اپ لوڈ کریں",
    health_profile: "ہیلتھ پروفائل",
    manage_health_info: "اپنی ذاتی صحت کی معلومات کا نظم کریں",
    basic_info: "بنیادی معلومات",
    height: "قد (cm)",
    weight: "وزن (kg)",
    blood_group: "بلڈ گروپ",
    medical_history: "طبی تاریخ",
    existing_conditions: "موجودہ حالات (مثلاً دل کا دورہ، شوگر)",
    past_surgeries: "پچھلی سرجری / ہسپتال میں داخل ہونا",
    lifestyle: "طرز زندگی",
    save_profile: "ہیلتھ پروفائل محفوظ کریں",
    upload_manage_health: "اپنی صحت کی دستاویزات اپ لوڈ اور ان کا نظم کریں",
    uploaded_by: "کی طرف سے اپ لوڈ করা گیا",
    view: "دیکھیں",
    download: "ڈاؤن لوڈ کریں",
    delete: "حذف کریں",
    choose_action: "ایک عمل منتخب کریں",
    upload_pdf_img: "پی ڈی ایف یا تصویر اپ لوڈ کریں",
    camera_scan: "کیمرہ (اسکین)",
    active_medications: "فعال ادویات",
    prescription_history: "نسخہ کی تاریخ",
    dr_dosage: "ڈاکٹر / خوراک",
    instruction: "ہدایت",
    ordered_on: "کو آرڈر کیا گیا",
    issued_by: "کی طرف سے جاری کیا گیا",
    order_meds: "ادویات آرڈر کریں",
    medical_prescription: "طبی نسخہ",
    reg_no: "رجسٹریشن نمبر",
    patient: "مریض",
    date: "تاریخ",
    age: "عمر",
    frequency: "تعدد",
    duration: "دورانیہ",
    instructions: "ہدایات",
    doctors_notes: "ڈاکٹر کے نوٹس",
    print: "پرنٹ کریں",
    low: "کم",
    moderate: "درمیانی",
    high: "زیادہ",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLangState] = useState<Language | null>(null);

  useEffect(() => {
    AsyncStorage.getItem("user-language").then((lang: string | null) => {
      if (lang) setLangState(lang as Language);
    });
  }, []);

  const setLanguage = (lang: Language) => {
    setLangState(lang);
    AsyncStorage.setItem("user-language", lang);
  };

  const t = (key: string) => {
    if (!language) return translations["en"][key] || key;
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};
